### ISSUE TITLE
mysql.slave_master_info error after upgrading to 5.7.14

### ISSUE THREAD

**Issue by karljohns0n** [iuscommunity-pkg/mysql57u#2]
Upgrading from 5.7.13 to 5.7.14 results in the following errors:

```
2016-08-24T17:55:46.773252Z 0 [ERROR] Info table has a problem with its key field(s). Table 'mysql.slave_master_info' expected field #23 to be 'Channel_name' but found 'Tls_version' instead.

2016-08-24T17:55:46.776789Z 0 [ERROR] Incorrect definition of table performance_schema.replication_connection_status: expected column 'RECEIVED_TRANSACTION_SET' at position 7 to have type longtext, found type text.

2016-08-24T17:55:46.777052Z 0 [ERROR] Incorrect definition of table performance_schema.replication_group_member_stats: expected column 'COUNT_TRANSACTIONS_ROWS_VALIDATING' at position 6, found 'COUNT_TRANSACTIONS_VALIDATING'.
```

Running mysql_upgrade fix the last two errors even if mysql_upgrade is rarely needed in the same branch. The last error already has a bug opened:

http://bugs.mysql.com/bug.php?id=82384

I guess we need to wait for an upstream patch. A workaround could be to dump/import.

**Comment by b-harper** [comment]
Hey @karljohns0n,

Thanks for taking the time to chat on IRC and submit this bug.  This does appear to be an upstream with no fix at this moment.  It is important to note, that it appears this issue only happens if the server was upgraded from 5.6 at some point.

I am subscribed to that mysql bug.  From my experience, mysql bugs do not get many updates after they have been able to reproduce the issue.  It would appear they use a different system to track the progress that is not publicly available.

-Ben

**Comment by b-harper** [comment]
That mysql bug got updated with a workaround.  It is not clear if the 'Owen Owen' user is form mysql or not, so that workaround may not be 'offical'.

**Comment by karljohns0n** [comment]
The workaround seems to fix the issue. It switch Tls_version at the end of the table. Best would be to compare this table with a fresh install.

![screen shot 2016-09-12 at 4 07 09 pm](https://cloud.githubusercontent.com/assets/13647791/18450940/ff5aaa42-7902-11e6-9a3e-ff1b3fa8903d.png)

**Comment by b-harper** [comment]
That mysql bug got another update.  It would seem that workaround does have issues with replication.

**Comment by b-harper** [comment]
For those not following the upstream bug, there has been another comment about upgrading to 5.7.15 and broken replication.  

There is a new release and the [5.7.16 change log](https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-16.html) do not show any entries regarding this issue.  The IUS mysql57u-5.7.16-1.ius packages will be hitting the testing repositories during tonight's automation run.

**Comment by b-harper** [comment]
[The upstream bug](https://bugs.mysql.com/bug.php?id=82384) has been updated with a possible solution:

```
mysql_upgrade --upgrade-system-tables
```

It is not clear if this is solution is coming from Oracle themselves or a just community member.

**Comment by b-harper** [comment]
[The upstream bug][0] got another update, with another possible workaround from a [Percona bug][1].

Again, it is not clear if this work around is coming from Percona or a just community member.


[0]: https://bugs.mysql.com/bug.php?id=82384
[1]: https://bugs.launchpad.net/percona-server/+bug/1617715

**Comment by b-harper** [comment]
According to the [5.7.17 change log][0], this issue has been fixed:

> Upgrading from MySQL 5.6 to 5.7.13 and then to 5.7.14 resulted in an incorrect column order in the mysql.slave_master_info system table. (Bug #24384561, Bug #82384)

This change log entry points to the now closed [bug][1] @karljohns0n mentioned earlier.  The mysql57u-5.7.17 packages are in the stable repositories.  

[0]: https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-17.html
[1]: https://bugs.mysql.com/bug.php?id=82384
