### ISSUE TITLE
mysql57u conflicts with mysql from OL6 

### ISSUE THREAD

**Issue by mi1os** [iuscommunity-pkg/mysql57u#3]
Hi,

when installing postfix on latest OL6 with both public OL6 repo and ius6 I've noticed conflict between
mysql57u and mysql as both satisfies postfix's requirement for libmysqlclient

                    Resolving Dependencies
                    --> Running transaction check
                    ---> Package postfix.x86_64 2:2.6.6-6.el6_7.1 will be installed
                    --> Processing Dependency: cyrus-sasl >= 2.1.10 for package: 2:postfix-2.6.6-6.el6_7.1.x86_64
                    --> Processing Dependency: mysql-libs for package: 2:postfix-2.6.6-6.el6_7.1.x86_64
                    --> Processing Dependency: libmysqlclient.so.16(libmysqlclient_16)(64bit) for package: 2:postfix-2.6.6-6.el6_7.1.x86_64
                    --> Processing Dependency: libmysqlclient.so.16()(64bit) for package: 2:postfix-2.6.6-6.el6_7.1.x86_64
                    --> Running transaction check
                    ---> Package cyrus-sasl.x86_64 0:2.1.23-15.el6_6.2 will be installed
                    ---> Package mysql-libs.x86_64 0:5.1.73-7.el6 will be installed
                    ---> Package mysql57u-libs.x86_64 0:5.7.16-1.ius.el6 will be installed
                    --> Processing Dependency: mysql57u-common(x86-64) = 5.7.16-1.ius.el6 for package: mysql57u-libs-5.7.16-1.ius.el6.x86_64
                    --> Running transaction check
                    ---> Package mysql57u-common.x86_64 0:5.7.16-1.ius.el6 will be installed
                    --> Processing Dependency: mysql57u-config(x86-64) = 5.7.16-1.ius.el6 for package: mysql57u-common-5.7.16-1.ius.el6.x86_64
                    --> Running transaction check
                    ---> Package mysql57u-config.x86_64 0:5.7.16-1.ius.el6 will be installed
                    --> Processing Conflict: mysql57u-config-5.7.16-1.ius.el6.x86_64 conflicts mysql-libs < 5.7.16-1.ius.el6
                    --> Processing Conflict: mysql57u-libs-5.7.16-1.ius.el6.x86_64 conflicts mysql-libs < 5.7.16-1.ius.el6
                    --> Finished Dependency Resolution
                    Error: mysql57u-config conflicts with mysql-libs-5.1.73-7.el6.x86_64
                    Error: mysql57u-libs conflicts with mysql-libs-5.1.73-7.el6.x86_64
                     You could try using --skip-broken to work around the problem
                     You could try running: rpm -Va --nofiles --nodigest

workaround was to install postfix and mysql-libs at the same time to prevent this collision.

Milos

**Comment by carlwgeorge** [comment]
IUS packages intentionally [provide and conflict with their stock counterparts](https://ius.io/SafeRepo/#safe-replacement-package).  The behavior you are seeing is expected.  Unfortunately the user experience isn't as smooth as it could be due to yum's inadequate dependency logic.  This has been significantly improved in dnf, however dnf has not been added to RHEL (or derivatives) yet.  The workaround you described is one option.  Another choice is to temporarily disable IUS while installing postfix.

```
yum --disablerepo ius install postfix
```
