### ISSUE TITLE
Error log should init after data directory initialize

### ISSUE THREAD

**Issue by hilyjiang** [iuscommunity-pkg/mysql57u#4]
or else, mysql-prepare-db-dir would failed:

```
[root@yyf6 libexec]# /usr/libexec/mysql-prepare-db-dir 
Initializing MySQL database
2017-06-15T04:00:36.564962Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2017-06-15T04:00:36.566510Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
2017-06-15T04:00:36.566530Z 0 [ERROR] Aborting

Initialization of MySQL database failed.
Perhaps /etc/my.cnf is misconfigured.
```

**Comment by carlwgeorge** [comment]
`mysql-prepare-db-dir` is not intended to be run directly by users, which is why it is in `/usr/libexec` instead of `/usr/bin`.  It is called by the sysvinit script with a particular set of arguments.  Can you elaborate on why you are running it directly and what the actual issue is?

**Comment by hilyjiang** [comment]
I use `systemctl start mysqld.service` to start mysql server, but it failed.
So I manually exec `mysql-prepare-db-dir` for debug, and find the reason.

**Comment by carlwgeorge** [comment]
We only provide mysql57u packages for EL6, which uses SysVinit.  What OS are you using?  Did you rebuild the packages yourself?

**Comment by hilyjiang** [comment]
Yes, I rebuild it for EL7.
I use CentOS 7, so it is the reason.

**Comment by carlwgeorge** [comment]
As I mentioned in #5, the systemd compatibility of this package is not a high priority for us.  If you are using CentOS 7, I recommend using our mariadb100u or mariadb101u packages instead.

**Comment by hilyjiang** [comment]
Thanks carlwgeorge.

I have manually adjust the initial order to temporarily fix it.
