### ISSUE TITLE
/var/log/mysqld.log permissions not set correctly

### ISSUE THREAD

**Issue by mshade** [iuscommunity-pkg/mysql57u#8]
https://github.com/iuscommunity-pkg/mysql57u/blob/b565f18ffe4d5d9abd3466a84c3fa217b40a8aa2/SOURCES/mysql-prepare-db-dir.sh#L49

Since the log file at /var/log/mysqld.log is provided by the -server package, it already exists, and the install command does not run. However, it is created as root:root. A previous version of the prepare-db-dir.sh script ran a chown on /var/log/mysqld.log to set correct permissions. Currently, the file is left owned root:root, and mysql cannot write to it, leading to a failure to start out of the box.

The specific package in question is: mysql57u-server-5.7.20-1.ius.centos6.x86_64

[issue previously mentioned missing /etc/my.cnf; did not realize this was provided bye a separate -config package now]

**Comment by b-harper** [comment]
@mshade,

Thanks for taking the time to report this issue.  I am able to recreate and will work on getting some updated packages built.

**Comment by b-harper** [comment]
@mshade,

Updated packages have been built and will hit the testing repositories during tonight's automation run.  I have done testing on a few different situations and I am pretty confident the new package addresses this issue.  The plan is to move the packages to the stable repositories early next week.

**Comment by mshade** [comment]
Thanks @b-harper! Glad to hear, and appreciate the fast action.

**Comment by b-harper** [comment]
The updated packages will get moved into the stable repositories during tonight's automation run.
